services:
  kafka-cluster:
    image: apache/kafka:latest
    hostname: kafka-cluster
    container_name: kafka-cluster
    ports:
      - "9092:9092"
    environment:
      # ------ Required KRaft properties ------ #

      # Assigns all roles for KRaft to single broker for local development. Should be separated for production.
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-cluster:29093

      # -------------- Listeners -------------- #

      KAFKA_LISTENERS: INTERNAL://kafka-cluster:29092, CONTROLLER://kafka-cluster:29093, EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-cluster:29092, EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # --------- Other configuration --------- #

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk # Fixed id.
      KAFKA_LOG_DIRS: /tmp/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - kafka-cluster
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-cluster:29092

  kafka-connect-datagen:
    image: cnfldemos/kafka-connect-datagen:0.6.7-8.0.0
    container_name: kafka-connect-datagen
    ports:
      - "8083:8083"
    depends_on:
      - kafka-cluster
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-cluster:29092
      CONNECT_GROUP_ID: kafka-connect-datagen

      # Mandatory for a new group.id.
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter

      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-datagen"
      CONNECT_REST_PORT: 8083

      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    volumes:
      - ${PWD}/datagen/schemas:/tmp/schemas